version: '3.3'

services:
   java-maven:
       build:
         context: .
         dockerfile: Dockerfile
       ports:
         - "8080:8080"
       networks:
         - mongodb
       tty: true
       command: top
   db:
     image: dubc/mongodb-3.4
     ports:
       - "27017:27017"
     networks:
       - mongodb
     restart: always
     
networks:
  mongodb:
    driver: bridge
